name: flutter_holo_date_picker
description: A Flutter package of Date Picker that looks like Holo Theme in Android.
version: 1.1.4
homepage: https://github.com/kfiross/flutter_holo_date_picker

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: